spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/hibernate-ex
    username: postgres
    password: mefA1evica

  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
      default_batch_fetch_size: 20
      jdbc.batch_size: 20
    show-sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
      context-path: "/api"
management:
  endpoints:
    web:
      exposure:
        include: "*"
